### PR TITLE
Fixes for recent sphinx and docutils versions

### PR DESCRIPTION
**Pull request by rjarry**

### CODE REVIEW

**Review by llucax — APPROVED** [review]
I will blindly merge this PR because I didn't actually use aafig for the last, at least, 8 years. If you or anybody else reading this want to take over maintainance, I'll happily give access :)

**Comment by llucax** [comment]
Thanks!

**Comment by rjarry** [comment]
Hi @llucax, thanks for merging :)

I don't have the time to take over the maintenance of yet another project, but I'll submit fixes if I can.

Btw, could you publish a new release with this fix to https://pypi.org ?

**Comment by llucax** [comment]
On Monday 18 June 2018 09:32:11 CEST Robin Jarry wrote:
> Hi @llucax, thanks for merging :)
> 
> I don't have the time to take over the maintenance of yet another
> project, but I'll submit fixes if I can.
> 
> Btw, could you publish a new release with this fix to https://pypi.org ?

Hi Robin. Sorry again for the delay. Today I tried to do the release in 
pypi but I'm bumping into problems because all the docs on how to do a 
release in the README are outdated. I don't have the time to dedicate to 
find out more and get me up to date in terms of pypi so sadly I won't be 
able to do a release.

Again, if you want to step up and help, you are welcome to take over the 
management of pypi, I'll gladly give you permissions to do so. Also if you 
can update the README to have precise instructions to make a release, I 
would try to find some time to retry it.

Sorry again for the troubles!

Thanks!

-- 
Leandro Lucarella (Luca)
https://llucax.com

**Pull request merged**
